apiVersion: v1
kind: Service
metadata:
  name: user-api
  namespace: callum-dev
spec:
  type: LoadBalancer
  selector:
    app: user-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000